# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e42209f39937d35173b8c64dcbf09a24c2fb12154d9c1558527170a8cf6e5bd1612dd9a31ad7397d64609755fe854d1d066d18fc855509788a4ebf6145bac043

test:
  secret_key_base: 1001c789b61d500ebc9e3d9b6d034b8b2b0ffc9b5998bce37fe3c22154d6cc665a1195e18917979bd1b8ebe485da62a2fd38129cd482b11a30792eef7a3b0e0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
